server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://XXXXXXX:3306/security?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: XXXXXXX
    database: 0
  jackson:
    serializaion:
      indent_output: true
  logging:
    level: INFO
  session:
    store-type: none
  thymeleaf:
    cache: false
security:
  basic:
    enabled: false

custom-security:
  browser:
    loginType: redirect
  code:
    image:
      length: 4
      width: 200

#    loginPage: custom-login.html
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type.descriptor.sql.BasicExtractor:TRACE
#    com.mypackage: DEBUG